<Project Sdk="Microsoft.NET.Sdk.Web"> <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
</PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" Version="2.60.0" /> </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\teledon.proto" GrpcServices="Server" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Teledon.Model\Teledon.Model.csproj" />
        <ProjectReference Include="..\Teledon.Persistence\Teledon.Persistence.csproj" />
        <ProjectReference Include="..\Teledon.Services\Teledon.Services.csproj" />
        <ProjectReference Include="..\Teledon.Networking\Teledon.Networking.csproj" />
    </ItemGroup>
</Project>